create extension if not exists vector;
create extension if not exists pg_trgm;

create table if not exists public.administrative_cases (
  id bigint generated by default as identity primary key,
  source_id text not null,
  case_number text,
  decision_date date,
  dispute_subject text,
  result text,
  appeal_type text,
  fullcase_url text,
  download_url text,
  full_text text,
  text_status text,
  palata integer default 0,
  court_branch text default 'administrative',
  source_page integer,
  scraped_at timestamptz,
  indexed_at timestamptz,
  embedding vector(1536),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  search_vector tsvector generated always as (
    to_tsvector(
      'simple',
      coalesce(case_number, '') || ' ' ||
      coalesce(dispute_subject, '') || ' ' ||
      coalesce(result, '') || ' ' ||
      coalesce(appeal_type, '') || ' ' ||
      coalesce(full_text, '')
    )
  ) stored
);

create unique index if not exists administrative_cases_source_id_uidx
  on public.administrative_cases (source_id);

create index if not exists administrative_cases_case_number_idx
  on public.administrative_cases (case_number);

create index if not exists administrative_cases_decision_date_idx
  on public.administrative_cases (decision_date desc);

create index if not exists administrative_cases_branch_idx
  on public.administrative_cases (court_branch);

create index if not exists administrative_cases_search_vector_gin_idx
  on public.administrative_cases using gin (search_vector);

create index if not exists administrative_cases_subject_trgm_idx
  on public.administrative_cases using gin (dispute_subject gin_trgm_ops);

create index if not exists administrative_cases_full_text_trgm_idx
  on public.administrative_cases using gin (full_text gin_trgm_ops);

create index if not exists administrative_cases_embedding_idx
  on public.administrative_cases using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

create or replace function public.set_administrative_cases_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_administrative_cases_updated_at on public.administrative_cases;

create trigger trg_administrative_cases_updated_at
before update on public.administrative_cases
for each row
execute function public.set_administrative_cases_updated_at();

alter table public.administrative_cases enable row level security;

drop policy if exists "Public can read administrative cases"
  on public.administrative_cases;

create policy "Public can read administrative cases"
  on public.administrative_cases
  for select
  to anon, authenticated
  using (true);

create or replace function public.match_administrative_cases(
  query_embedding vector(1536),
  match_count int default 5
)
returns table (
  id bigint,
  case_number text,
  decision_date date,
  dispute_subject text,
  result text,
  appeal_type text,
  fullcase_url text,
  download_url text,
  full_text text,
  similarity double precision
)
language sql
stable
set search_path = public, extensions
as $$
  select
    ac.id,
    ac.case_number,
    ac.decision_date,
    ac.dispute_subject,
    ac.result,
    ac.appeal_type,
    ac.fullcase_url,
    ac.download_url,
    ac.full_text,
    1 - (ac.embedding <=> query_embedding) as similarity
  from public.administrative_cases as ac
  where ac.embedding is not null
  order by ac.embedding <=> query_embedding
  limit greatest(coalesce(match_count, 5), 0);
$$;

create or replace function public.match_administrative_cases_filtered(
  query_embedding vector(1536),
  search_text text default null,
  match_count int default 8
)
returns table (
  id bigint,
  case_number text,
  decision_date date,
  dispute_subject text,
  result text,
  appeal_type text,
  fullcase_url text,
  download_url text,
  full_text text,
  similarity double precision
)
language sql
stable
set search_path = public, extensions
as $$
  select
    ac.id,
    ac.case_number,
    ac.decision_date,
    ac.dispute_subject,
    ac.result,
    ac.appeal_type,
    ac.fullcase_url,
    ac.download_url,
    ac.full_text,
    1 - (ac.embedding <=> query_embedding) as similarity
  from public.administrative_cases as ac
  where ac.embedding is not null
    and (
      nullif(trim(search_text), '') is null
      or ac.search_vector @@ plainto_tsquery('simple', search_text)
      or ac.dispute_subject ilike '%' || search_text || '%'
      or ac.full_text ilike '%' || search_text || '%'
    )
  order by ac.embedding <=> query_embedding
  limit greatest(coalesce(match_count, 8), 0);
$$;
