-- ============================================================
-- Legal search backend migration
-- Run this in Supabase SQL Editor.
-- Adds:
--   1. case_legal_profiles starter table
--   2. profile/search indexes
--   3. search_administrative_cases_hybrid RPC
-- ============================================================

create extension if not exists pg_trgm;

-- Optional normalized legal profile for each decision.
-- This table is intentionally separate from administrative_cases so the
-- original import table can stay stable while profiles are generated/rebuilt.
create table if not exists public.case_legal_profiles (
  id bigint generated by default as identity primary key,
  case_id bigint not null references public.administrative_cases(id) on delete cascade,
  category text not null default 'ადმინისტრაციული',
  legal_institution text,
  legal_institution_code text,
  dispute_subject text,
  special_law text,
  legal_articles text[] not null default '{}',
  administrative_body text,
  procedural_stage text,
  strict_keywords text[] not null default '{}',
  broad_keywords text[] not null default '{}',
  must_match_terms text[] not null default '{}',
  exclude_terms text[] not null default '{}',
  facts_summary text,
  legal_issue text,
  profile_json jsonb not null default '{}'::jsonb,
  search_vector tsvector not null default ''::tsvector,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (case_id)
);

create index if not exists case_legal_profiles_case_id_idx
  on public.case_legal_profiles(case_id);

create index if not exists case_legal_profiles_institution_idx
  on public.case_legal_profiles(legal_institution);

create index if not exists case_legal_profiles_institution_trgm_idx
  on public.case_legal_profiles using gin (legal_institution gin_trgm_ops);

create index if not exists case_legal_profiles_subject_trgm_idx
  on public.case_legal_profiles using gin (dispute_subject gin_trgm_ops);

create index if not exists case_legal_profiles_search_vector_gin_idx
  on public.case_legal_profiles using gin (search_vector);

create index if not exists administrative_cases_search_vector_gin_idx
  on public.administrative_cases using gin (search_vector);

create or replace function public.refresh_case_legal_profile_search_vector()
returns trigger
language plpgsql
as $$
begin
  new.search_vector :=
    setweight(to_tsvector('simple', coalesce(new.legal_institution, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(new.dispute_subject, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(new.administrative_body, '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(new.special_law, '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(array_to_string(new.legal_articles, ' '), '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(array_to_string(new.strict_keywords, ' '), '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(array_to_string(new.must_match_terms, ' '), '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(array_to_string(new.broad_keywords, ' '), '')), 'C') ||
    setweight(to_tsvector('simple', coalesce(new.facts_summary, '')), 'D') ||
    setweight(to_tsvector('simple', coalesce(new.legal_issue, '')), 'C');

  return new;
end;
$$;

drop trigger if exists trg_case_legal_profiles_search_vector on public.case_legal_profiles;

create trigger trg_case_legal_profiles_search_vector
before insert or update of
  legal_institution,
  dispute_subject,
  administrative_body,
  special_law,
  legal_articles,
  strict_keywords,
  must_match_terms,
  broad_keywords,
  facts_summary,
  legal_issue
on public.case_legal_profiles
for each row
execute function public.refresh_case_legal_profile_search_vector();

create or replace function public.set_case_legal_profiles_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_case_legal_profiles_updated_at on public.case_legal_profiles;

create trigger trg_case_legal_profiles_updated_at
before update on public.case_legal_profiles
for each row
execute function public.set_case_legal_profiles_updated_at();

alter table public.case_legal_profiles enable row level security;

drop policy if exists "Public can read legal profiles" on public.case_legal_profiles;

create policy "Public can read legal profiles"
  on public.case_legal_profiles
  for select
  to anon, authenticated
  using (true);

-- Georgian FTS currently uses the simple dictionary. To improve recall without
-- a Georgian stemmer, we convert meaningful words to prefix lexemes:
--   "თანამემამულის სტატუსი" -> თანამემა:* & სტატუსი:*
create or replace function public.legal_build_prefix_tsquery(
  terms text[],
  max_terms int default 12
)
returns tsquery
language plpgsql
immutable
as $$
declare
  term text;
  word text;
  clean text;
  roots text[];
  pieces text[] := '{}';
  q text;
  generic_prefixes constant text[] := array[
    'სასამართ', 'გადაწყვე', 'ადმინისტ', 'სამართლ', 'სამართა',
    'საქართვ', 'კანონის', 'პირველი', 'პუნქტის', 'ქვეპუნქ',
    'კანონი', 'მუხლის', 'სარჩელ', 'მოსარჩ', 'მოპასუ', 'განჩინე',
    'საქმის', 'სტატუს'
  ];
begin
  if terms is null or array_length(terms, 1) is null then
    return null;
  end if;

  foreach term in array terms loop
    exit when array_length(pieces, 1) >= greatest(max_terms, 1);
    roots := '{}';

    foreach word in array regexp_split_to_array(coalesce(term, ''), '\s+') loop
      clean := regexp_replace(lower(word), '[^0-9a-zა-ჿ]+', '', 'g');

      if length(clean) < 5 then
        continue;
      end if;

      if exists (
        select 1
        from unnest(generic_prefixes) as gp(prefix)
        where clean like gp.prefix || '%'
      ) then
        continue;
      end if;

      clean := substring(clean from 1 for 8) || ':*';

      if not clean = any(roots) then
        roots := roots || clean;
      end if;

      exit when array_length(roots, 1) >= 3;
    end loop;

    if array_length(roots, 1) = 1 then
      pieces := pieces || roots[1];
    elsif array_length(roots, 1) > 1 then
      pieces := pieces || ('(' || array_to_string(roots, ' & ') || ')');
    end if;
  end loop;

  if array_length(pieces, 1) is null then
    return null;
  end if;

  q := array_to_string(pieces, ' | ');

  begin
    return to_tsquery('simple', q);
  exception when others then
    return null;
  end;
end;
$$;

create or replace function public.legal_compact_terms(terms text[])
returns text[]
language sql
immutable
as $$
  select coalesce(array_agg(distinct cleaned order by cleaned), '{}')
  from (
    select nullif(trim(regexp_replace(term, '\s+', ' ', 'g')), '') as cleaned
    from unnest(coalesce(terms, '{}')) as t(term)
  ) s
  where cleaned is not null and length(cleaned) > 2;
$$;

drop function if exists public.search_administrative_cases_hybrid(
  text, text, text, text[], text, text[], text[], text[], text[], int
);

create function public.search_administrative_cases_hybrid(
  p_legal_institution text default null,
  p_dispute_subject text default null,
  p_special_law text default null,
  p_legal_articles text[] default '{}',
  p_administrative_body text default null,
  p_must_match_terms text[] default '{}',
  p_exclude_terms text[] default '{}',
  p_strict_keywords text[] default '{}',
  p_broad_keywords text[] default '{}',
  p_limit int default 20
)
returns table (
  id text,
  case_number text,
  decision_date text,
  dispute_subject text,
  result text,
  appeal_type text,
  fullcase_url text,
  download_url text,
  full_text text,
  court_branch text,
  legal_institution text,
  administrative_body text,
  special_law text,
  ts_rank real,
  final_score real,
  search_mode text
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_strict_terms text[];
  v_broad_terms text[];
  v_must_terms text[];
  v_exclude_terms text[];
  v_strict_q tsquery;
  v_broad_q tsquery;
  v_main_q tsquery;
  v_institution_q tsquery;
  v_max_rows int;
begin
  v_max_rows := least(greatest(coalesce(p_limit, 20), 1), 100);

  v_strict_terms := public.legal_compact_terms(
    coalesce(p_strict_keywords, '{}') ||
    coalesce(p_must_match_terms, '{}') ||
    array[
      p_legal_institution,
      p_dispute_subject,
      p_special_law,
      p_administrative_body
    ] ||
    coalesce(p_legal_articles, '{}')
  );

  v_broad_terms := public.legal_compact_terms(coalesce(p_broad_keywords, '{}'));
  v_must_terms := public.legal_compact_terms(coalesce(p_must_match_terms, '{}'));
  v_exclude_terms := public.legal_compact_terms(coalesce(p_exclude_terms, '{}'));

  v_strict_q := public.legal_build_prefix_tsquery(v_strict_terms, 14);
  v_broad_q := public.legal_build_prefix_tsquery(v_broad_terms, 10);
  v_institution_q := public.legal_build_prefix_tsquery(array[p_legal_institution], 3);
  v_main_q := coalesce(v_strict_q, v_broad_q);

  -- No random/recent fallback. If there is no meaningful query, return zero rows.
  if v_main_q is null then
    return;
  end if;

  return query
  with candidates as (
    select
      a.*,
      p.legal_institution as profile_legal_institution,
      p.administrative_body as profile_administrative_body,
      p.special_law as profile_special_law,
      p.search_vector as profile_search_vector,
      (
        ts_rank_cd(a.search_vector, v_main_q) +
        coalesce(ts_rank_cd(p.search_vector, v_main_q), 0)
      )::real as base_rank,
      (
        case
          when v_strict_q is not null and a.search_vector @@ v_strict_q then 2.0
          when v_strict_q is not null and p.search_vector @@ v_strict_q then 2.0
          else 0
        end +
        case
          when v_broad_q is not null and a.search_vector @@ v_broad_q then 0.5
          when v_broad_q is not null and p.search_vector @@ v_broad_q then 0.5
          else 0
        end +
        case
          when v_institution_q is not null and (
            a.search_vector @@ v_institution_q or
            p.search_vector @@ v_institution_q or
            coalesce(a.full_text, '') ilike '%' || p_legal_institution || '%' or
            coalesce(a.dispute_subject, '') ilike '%' || p_legal_institution || '%' or
            coalesce(p.legal_institution, '') ilike '%' || p_legal_institution || '%'
          ) then 3.0
          else 0
        end +
        case
          when nullif(trim(coalesce(p_administrative_body, '')), '') is not null and (
            coalesce(a.full_text, '') ilike '%' || p_administrative_body || '%' or
            coalesce(a.dispute_subject, '') ilike '%' || p_administrative_body || '%' or
            coalesce(p.administrative_body, '') ilike '%' || p_administrative_body || '%'
          ) then 1.0
          else 0
        end
      )::real as boost_score
    from public.administrative_cases a
    left join public.case_legal_profiles p on p.case_id = a.id
    where
      (
        a.search_vector @@ v_main_q or
        p.search_vector @@ v_main_q
      )
      -- If a legal institution was identified, it is a hard gate.
      and (
        nullif(trim(coalesce(p_legal_institution, '')), '') is null
        or v_institution_q is null
        or a.search_vector @@ v_institution_q
        or p.search_vector @@ v_institution_q
        or coalesce(a.full_text, '') ilike '%' || p_legal_institution || '%'
        or coalesce(a.dispute_subject, '') ilike '%' || p_legal_institution || '%'
        or coalesce(p.legal_institution, '') ilike '%' || p_legal_institution || '%'
      )
      -- Must-match terms are evaluated before LIMIT.
      and not exists (
        select 1
        from unnest(v_must_terms) as mt(term)
        where not (
          coalesce(a.full_text, '') ilike '%' || mt.term || '%'
          or coalesce(a.dispute_subject, '') ilike '%' || mt.term || '%'
          or coalesce(p.legal_institution, '') ilike '%' || mt.term || '%'
          or coalesce(p.dispute_subject, '') ilike '%' || mt.term || '%'
          or (
            public.legal_build_prefix_tsquery(array[mt.term], 1) is not null
            and (
              a.search_vector @@ public.legal_build_prefix_tsquery(array[mt.term], 1)
              or p.search_vector @@ public.legal_build_prefix_tsquery(array[mt.term], 1)
            )
          )
        )
      )
      -- Exclusions are evaluated before LIMIT.
      and not exists (
        select 1
        from unnest(v_exclude_terms) as et(term)
        where
          coalesce(a.full_text, '') ilike '%' || et.term || '%'
          or coalesce(a.dispute_subject, '') ilike '%' || et.term || '%'
          or coalesce(p.legal_institution, '') ilike '%' || et.term || '%'
          or coalesce(p.dispute_subject, '') ilike '%' || et.term || '%'
          or (
            public.legal_build_prefix_tsquery(array[et.term], 1) is not null
            and (
              a.search_vector @@ public.legal_build_prefix_tsquery(array[et.term], 1)
              or p.search_vector @@ public.legal_build_prefix_tsquery(array[et.term], 1)
            )
          )
      )
  )
  select
    c.id::text,
    c.case_number::text,
    c.decision_date::text,
    c.dispute_subject::text,
    c.result::text,
    c.appeal_type::text,
    c.fullcase_url::text,
    c.download_url::text,
    left(c.full_text, 3000)::text,
    c.court_branch::text,
    c.profile_legal_institution::text,
    c.profile_administrative_body::text,
    c.profile_special_law::text,
    c.base_rank::real,
    (c.base_rank + c.boost_score)::real as final_score,
    case when v_strict_q is not null then 'fts_legal_profile_strict' else 'fts_legal_profile_broad' end::text
  from candidates c
  order by (c.base_rank + c.boost_score) desc, c.decision_date desc nulls last
  limit v_max_rows;
end;
$$;

grant execute on function public.search_administrative_cases_hybrid(
  text, text, text, text[], text, text[], text[], text[], text[], int
) to anon, authenticated, service_role;

-- Quick smoke test after deploying:
-- select id, dispute_subject, final_score, search_mode
-- from public.search_administrative_cases_hybrid(
--   p_legal_institution => 'თანამემამულის სტატუსი',
--   p_must_match_terms => array['თანამემამულის სტატუსი'],
--   p_exclude_terms => array['ლტოლვილი', 'საერთაშორისო დაცვა'],
--   p_strict_keywords => array['თანამემამულის სტატუსის მინიჭება'],
--   p_limit => 10
-- );
